// global state
export const SET_DEFAULT = 'SET_DEFAULT';
export const SET_FINISHED_ONBOARDING = 'SET_FINISHED_ONBOARDING';

// movie
export const SET_MOVIE_LIST = 'SET_MOVIE_LIST';
export const SET_MOVIE_LIST_RESET = 'SET_MOVIE_LIST_RESET';
export const SET_MOVIE_DETAIL = 'SET_MOVIE_DETAIL';

export const SET_MOVIE_POPULAR_LIST = 'SET_MOVIE_POPULAR_LIST';
export const SET_MOVIE_POPULAR_LIST_RESET = 'SET_MOVIE_POPULAR_LIST_RESET';

export const SET_MOVIE_THEATER_LIST = 'SET_MOVIE_THEATER_LIST';
export const SET_MOVIE_THEATER_LIST_RESET = 'SET_MOVIE_THEATER_LIST_RESET';
